# Generated by Django 4.2.7 on 2023-11-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqli', '0003_alter_chatroom_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sender',
            field=models.CharField(max_length=1000),
        ),
    ]
